#!/bin/sh
KERNELVER="${KERNELVER:-6.12}"
export KERNELVER

DEFAULT_VMNAME="gccvm"
VMNAME="${VMNAME:-$DEFAULT_VMNAME}"
export VMNAME

SRCPATH="${SRCPATH:-$(realpath ./src)}"
export SRCPATH

BUILDPATH="${BUILDPATH:-$(realpath -m ./build)}"
export BUILDPATH

IMAGESPATH="${IMAGESPATH:-${BUILDPATH}/images}"
VMPATH="${VMPATH:-${IMAGESPATH}/${VMNAME}}"
export VMPATH

BUILDCACHE="${BUILDCACHE:-${BUILDPATH}/cache}"
CACHEPATH="${CACHEPATH:-${BUILDCACHE}/${VMNAME}}"
export CACHEPATH

KERNELSPATH="${KERNELSPATH:-${SRCPATH}/kernel-configs}"
KERNELCONFIG="${KERNELCONFIG:-${KERNELSPATH}/qemu-small-virtiofs-no-tcp}"
export KERNELCONFIG
