name: upinevm CI

on:
  push:
    tags:
      - "v*"
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-base:
    strategy:
      matrix:
        vmname:
          - gccvm
          - minimal
          - fossil

    uses: ./.github/workflows/reusable-build.yml
    with:
      vmname: ${{ matrix.vmname }}
