name: upinevm CI

on:
  push:
    tags:
      - "v*"
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-base:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        vmname:
          - gccvm
          - minimal
          - fossil
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: musl-gcc compile and strip
        run: |
          sudo apt-get update && sudo apt-get install -y musl-tools libelf-dev nasm
          if ! which flex ; then
            sudo apt-get update && sudo apt-get install -y flex bison
          fi

      - name: print env
        run: |
          echo ${{ matrix.vmname }}
          echo $(uname -a)
          env | sort | awk '{print $1}'

      - name: touch
        run: |
          mkdir -pv ./build/images/${{ matrix.vmname }}
          touch ./build/images/${{ matrix.vmname }}/test.txt

      # - name: build ${{ matrix.vmname }}
      #   run: |
      #     ./build.sh ${{ matrix.vmname }}

      - name: package ${{ matrix.vmname }}
        run: |
          mkdir -pv ./dist
          zip -r ./dist/${{ matrix.vmname }}.zip ./build/images/${{ matrix.vmname }}

      - name: Release ${{ matrix.vmname }}
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./dist/*
