name: upinevm CI

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build-base:
    strategy:
      matrix:
        vmname:
          - gccvm
          - minimal
          - fossil

    uses: ./.github/workflows/reusable-build.yml
    with:
      vmname: ${{ matrix.vmname }}

  release:
    needs: build-base
    runs-on: ubuntu-latest
    strategy:
      matrix:
        vmname:
          - gccvm
          - minimal
          - fossil
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build-base.outputs.vmname }}
      - name: ls
        run: |
          ls -l

      - name: release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ needs.build-base.outputs.vmname }}
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
