name: Reusable Build

on:
  workflow_call:
    inputs:
      vmname:
        required: true
        type: string

jobs:
  build-base:
    strategy:
      matrix:
        vmname:
          - gccvm
          - minimal
          - fossil

    uses: ./.github/workflows/reusable-build.yml
    with:
      vmname: ${{ matrix.vmname }}
